apiVersion: v1
kind: Service
metadata:
  name: netpol-test-dev
  namespace: dev
spec:
  selector:
    app: netpol-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netpol-test-stage
  namespace: stage
spec:
  selector:
    app: netpol-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netpol-test-prod
  namespace: prod
spec:
  selector:
    app: netpol-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80