apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-with-root
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"      # 0.5 CPU
            memory: "512Mi"  # 512 MB memory limit
          requests:
            cpu: "200m"      # 0.2 CPU
            memory: "256Mi"  # 256 MB memory request
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: test-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-test