apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-encrypt-secrets
  annotations:
    policies.kyverno.io/title: "Enforce Secret Encryption"
    policies.kyverno.io/category: "Secret Management Standards"
    policies.kyverno.io/severity: "critical"
    policies.kyverno.io/description: >-
      Ensures all Kubernetes secrets are properly encrypted to protect sensitive 
      information at rest. This policy enforces the use of encryption annotations 
      and validates proper encryption configuration to maintain security compliance
      and protect against unauthorized access to sensitive data.
    policies.kyverno.io/subject: "Secret"
    policies.kyverno.io/minversion: "1.13.0"
    policies.kyverno.io/policyversion: "1.0.1"
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: check-encryption
      match:
        resources:
          kinds:
            - Secret
      exclude:
        resources:
          namespaces:
            - kube-system  # Exclude system namespaces
          names:
            - "default-token-*"  # Exclude default service account tokens
      validate:
        message: "Secrets must be encrypted with proper annotations. Add the encryption annotation: 'encryption.kyverno.io/status: encrypted'"
        pattern:
          metadata:
            annotations:
              "encryption.kyverno.io/status": "encrypted"
    - name: validate-secret-type
      match:
        resources:
          kinds:
            - Secret
      validate:
        message: "Secret type must be Opaque, kubernetes.io/tls, or kubernetes.io/dockerconfigjson"
        pattern:
          type: "{{ regex_match('Opaque|kubernetes.io/tls|kubernetes.io/dockerconfigjson') }}"